- name: aws provison play
  hosts: localhost
  tasks:
    - name: bring up task
      ec2:
        aws_access_key: "{{ ansible_env.SNAWSCLICONFIG_INTEGRATION_AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ ansible_env.SNAWSCLICONFIG_INTEGRATION_AWS_SECRET_ACCESS_KEY }}"
        region: us-west-2
        key_name: scriptnull-key
        instance_type: t2.micro
        image: ami-7c803d1c
        wait: yes
        group: launch-wizard-1
        count: 1
        vpc_subnet_id: subnet-08a59a7e
        assign_public_ip: yes
