resources:
#   - name: u_git_resource
#     type: gitRepo
#     repoPath: scriptnull/sample_node
#     configuration:
#       integrationName: github
#       branches:
#         only: j-gitrepo
#     initialVersion:
#       sha: j-gitrepo
      
#   - name: u_out_webhook
#     type: webhook
#     configuration:
#       integrationName: out-webhook-int
#     initialVersion:
#       payload: "hello"
      
  - name: u_u16node_img
    type: image
    imageName: drydock/u16node
    configuration:
      integrationName: dockerint
    version:
      imageTag: master

pipelines:
  - name: test_u16_pipeline
    steps:
      - name: start_u16
        type: bash
        requires:
          resources:
            - u_u16node_img
        execution:
          onExecute:
            - echo "hi"
            
            
############### Environment variable testing ########################

      - name: start_u16_env
        type: bash
        requires:
          steps:
            - start_u16
        execution:
          onExecute:
            - echo "TODO"
            
      - name: restricted_envs
        type: bash
        requires:
          steps:
            - start_u16_env
        execution:
          onExecute:
            - printenv
            - echo "$STEP_ID"
            - echo "$STEP_NAME"
            - echo "$STEP_TYPE"
            - echo "$STEP_URL"
            - echo "$PIPELINE_NAME"
            - echo "$RUN_ID"
            - echo "$RUN_NUMBER"
            - echo "$STATUS_DIR"
            - echo "$STEPLET_ID"
            - echo "$STEP_JSON_PATH"
            - echo "$STEPLET_SCRIPT_PATH"
            - echo "$REQEXEC_BIN_PATH"
            - echo "$RUN_DIR"
            - echo "$STEP_DEPENDENCY_STATE_DIR"
            - echo "$STEP_OUTPUT_DIR"
            - echo "$STEP_WORKSPACE_DIR"
            - echo "$PIPELINE_WORKSPACE_DIR"
            - echo "$STEP_TMP_DIR"
            - echo "$OPERATING_SYSTEM"
            - echo "$ARCHITECTURE"
            - echo "$REQEXEC_DIR"
            - echo "$SHIPPABLE_API_URL"
            - echo "$BUILDER_API_TOKEN"
            - echo "$NO_VERIFY_SSL"
            - echo "$STEP_DOCKER_CONTAINER_NAME"


      - name: restricted_envs_in_step_exection
        type: bash
        triggeredBy:
          steps:
            - start_u16_env
        execution:
          onExecute:
            - printenv
            - echo "$STEP_ID"
            - STEP_ID=50
            - echo "step above this should fail"
            
            
      - name: restricted_envs_in_setup_env_yml
        type: bash
        triggeredBy:
          steps:
            - start_u16_env
        setup:
          environmentVariables:
            normal:
              STEP_TYPE: update
              STEP_NAME: update
              PIPELINE_NAME: update
        execution:
          onExecute:
            - printenv

############### Running build on image testing ########################

      - name: start_u16_img
        type: bash
        requires:
          steps:
            - start_u16
        execution:
          onExecute:
            - echo "TODO"
            
      - name: basic_custom_img
        type: bash
        requires:
          steps:
            - start_u16
        setup:
          runtime:
            type: image
            image:
              custom:
                name: scriptnull/custom
                tag: latest
        execution:
          onExecute:
            - echo "hi"
            - printenv

