resources:
#   - name: u_git_resource
#     type: gitRepo
#     repoPath: scriptnull/sample_node
#     configuration:
#       integrationName: github
#       branches:
#         only: j-gitrepo
#     initialVersion:
#       sha: j-gitrepo
      
#   - name: u_out_webhook
#     type: webhook
#     configuration:
#       integrationName: out-webhook-int
#     initialVersion:
#       payload: "hello"
      
  - name: u_u16node_img
    type: image
    imageName: drydock/u16node
    configuration:
      integrationName: dockerint
    version:
      imageTag: master

pipelines:
  - name: test_u16_pipeline
    steps:
      - name: start_u16
        type: bash
        requires:
          resources:
            - u_u16node_img
        execution:
          onExecute:
            - echo "hi"

      - name: start_u16_env
        type: bash
        requires:
          steps:
            - start_u16
        execution:
          onExecute:
            - echo "TODO"
