jobs:
  - name: ecs-man
    type: manifest
    steps:
      - GET: ecs-nginx

  - name: ecs-jatin-bg-deploy
    type: ecsDeploy
    options:
      deployMethod: blueGreen
    steps:
      - GET: ecs-man
      - GET: ecs-cluster
