jobs:
  # - name: sn-al-ship-man
  #   type: manifest
  #   steps:
  #     - IN: sn-al-ship-myapp3
  #     - IN: sn-al-ship-docker-opts-2
  #     - IN: sn-al-ship-trigger-1
  #
  # - name: sn-al-ship-ecs-dep-2
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-man
  #     - IN: sn-al-ship-ecs-cluster
  #     - IN: sn-al-ship-lb-1
  #       applyTo:
  #         - manifest: sn-al-ship-man
  #           image: sn-al-ship-myapp3
  #           port: 80
  #     - TASK: managed
  #       deployMethod: replace

  # - name: sn-al-ship-tri-man
  #   type: manifest
  #   steps:
  #     - IN: sn-al-ship-dk
  #     # - IN: sn-al-ship-tesing-do
  #     - IN: sn-al-ship-tm-trigger
  #
  # - name: sn-al-ship-tri-dep-1
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-tri-man
  #     - IN: sn-al-ship-tri-cluster
  #
  # - name: sn-al-ship-tri-man-2
  #   type: manifest
  #   steps:
  #     - IN: sn-al-ship-ep
  #     - IN: sn-al-ship-tm-trigger-2
  #
  # - name: sn-al-ship-tri-dep-2
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-tri-man-2
  #     - IN: sn-al-ship-tri-cluster

  # - name: sn-al-ship-gke-man
  #   type: manifest
  #   steps:
  #     - IN: sn-al-ship-dk
  #     - IN: sn-al-ship-docker-opts-2
  #     - IN: sn-al-ship-gke-trigger
  #
  # - name: sn-al-ship-gke-dep
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-gke-man
  #     - IN: sn-al-ship-gke-cluster
  #
  #
  - name: sn-al-ship-ddc-man
    type: manifest
    steps:
      - IN: sn-al-ship-ep
      - IN: sn-al-ship-ddc-trigger

  - name: sn-al-ship-ddc-dep
    type: deploy
    steps:
      - IN: sn-al-ship-ddc-man
      - IN: sn-al-ship-ddc-cluster

  - name: sn-al-ship-release-ddc
    type: release
    steps:
      - IN: sn-al-ship-ddc-dep
      - IN: sn-al-ship-version

  #
  # - name: sn-al-ship-ecs-man-bg
  #   type: manifest
  #   steps:
  #     - IN: sn-al-ship-myapp3
  #     - IN: sn-al-ship-do
  #     - IN: sn-al-ship-ecs-trigger
  #
  # - name: sn-al-ship-ecs-deploy-bg
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-ecs-man-bg
  #     - IN: sn-al-ship-ecs-cluster
  #     - IN: q-lb-loadbalancer1
  #       applyTo:
  #         - manifest: sn-al-ship-ecs-man-bg
  #           image: sn-al-ship-myapp3
  #           port: 80
