jobs:
  # - name: sn-rc-ship-man
  #   type: manifest
  #   steps:
  #     - IN: sn-rc-ship-myapp3
  #     - IN: sn-rc-ship-docker-opts-2
  #     - IN: sn-rc-ship-trigger-1
  #
  # - name: sn-rc-ship-ecs-dep-2
  #   type: deploy
  #   steps:
  #     - IN: sn-rc-ship-man
  #     - IN: sn-rc-ship-ecs-cluster
  #     - IN: sn-rc-ship-lb-1
  #       applyTo:
  #         - manifest: sn-rc-ship-man
  #           image: sn-rc-ship-myapp3
  #           port: 80
  #     - TASK: managed
  #       deployMethod: replace

  # - name: sn-rc-ship-tri-man
  #   type: manifest
  #   steps:
  #     - IN: sn-rc-ship-dk
  #     # - IN: sn-rc-ship-tesing-do
  #     - IN: sn-rc-ship-tm-trigger
  #
  # - name: sn-rc-ship-tri-dep-1
  #   type: deploy
  #   steps:
  #     - IN: sn-rc-ship-tri-man
  #     - IN: sn-rc-ship-tri-cluster
  #
  # - name: sn-rc-ship-tri-man-2
  #   type: manifest
  #   steps:
  #     - IN: sn-rc-ship-ep
  #     - IN: sn-rc-ship-tm-trigger-2
  #
  # - name: sn-rc-ship-tri-dep-2
  #   type: deploy
  #   steps:
  #     - IN: sn-rc-ship-tri-man-2
  #     - IN: sn-rc-ship-tri-cluster

  # - name: sn-rc-ship-gke-man
  #   type: manifest
  #   steps:
  #     - IN: sn-rc-ship-dk
  #     - IN: sn-rc-ship-docker-opts-2
  #     - IN: sn-rc-ship-gke-trigger
  #
  # - name: sn-rc-ship-gke-dep
  #   type: deploy
  #   steps:
  #     - IN: sn-rc-ship-gke-man
  #     - IN: sn-rc-ship-gke-cluster
  #
  #
  # - name: sn-rc-ship-ddc-man
  #   type: manifest
  #   steps:
  #     - IN: sn-rc-ship-ep
  #     - IN: sn-rc-ship-docker-opts-3
  #     - IN: sn-rc-ship-ddc-trigger
  #
  # - name: sn-rc-ship-ddc-dep
  #   type: deploy
  #   steps:
  #     - IN: sn-rc-ship-ddc-man
  #     - IN: sn-rc-ship-ddc-cluster
  #

  - name: sn-rc-ship-dcl-man
    type: manifest
    steps:
      - IN: sn-rc-ship-myapp2
      - IN: sn-rc-ship-dcl-trigger

  - name: sn-rc-ship-dcl-dep
    type: deploy
    steps:
      - IN: sn-rc-ship-dcl-man
      - IN: sn-rc-ship-dcl-cluster

  - name: sn-rc-ship-rel-man-xx
    type: manifest
    steps:
      - IN: sn-rc-ship-myapp3

  - name: sn-rc-ship-dcl-dep-yy
    type: deploy
    steps:
      - IN: sn-rc-ship-rel-man-xx
      - IN: sn-rc-ship-dcl-cluster

  - name: sn-rc-ship-release-5
    type: release
    steps:
      - IN: sn-rc-ship-version
      - IN: sn-rc-ship-dcl-dep-yy
      - TASK: managed
        bump: patch

  - name: sn-rc-ship-dcl-dep-subseq
    type: deploy
    steps:
      - IN: sn-rc-ship-release
      - IN: sn-rc-ship-dcl-cluster

  # - name: sn-rc-ship-ecs-man-bg
  #   type: manifest
  #   steps:
  #     - IN: sn-rc-ship-myapp3
  #     - IN: sn-rc-ship-do
  #     - IN: sn-rc-ship-ecs-trigger
  #
  # - name: sn-rc-ship-ecs-deploy-bg
  #   type: deploy
  #   steps:
  #     - IN: sn-rc-ship-ecs-man-bg
  #     - IN: sn-rc-ship-ecs-cluster
  #     - IN: q-lb-loadbalancer1
  #       applyTo:
  #         - manifest: sn-rc-ship-ecs-man-bg
  #           image: sn-rc-ship-myapp3
  #           port: 80

  - name: sn-rc-ship-kube-man
    type: manifest
    steps:
      - IN: sn-rc-ship-myapp2
      - IN: sn-rc-ship-kube-trigger

  - name: sn-rc-ship-kube-dep
    type: deploy
    steps:
      - IN: sn-rc-ship-kube-man
      - IN: sn-rc-ship-kube-cluster

  # - name: sn-rc-ship-provision-kube
  #   type: provision
  #   steps:
  #     - IN: sn-rc-kube-service-lb
