resources:
  - name: sample_img	
    type: image	
    imageName: scriptnull/sample_node	
    configuration:	
      integrationName: dockerint	
    initialVersion:	
      imageTag: latest

pipelines:
  - name: test_pipeline
    steps:
      - name: say_hi
        type: bash
        triggeredBy:	
          resources:	
            - sample_img
        execution:
          onExecute:
            - echo "hi"
