triggers:
  - name: sn-kube-trigger
    type: trigger
    version:
      counter: 4

  # - name: sn-file-trigger
  #   type: trigger
  #   version:
  #     counter: 12
  #
  # - name: sn-vici-trigger
  #   type: trigger
  #   version:
  #     counter: 2

  # - name: sn-trigger-1
  #   type: trigger
  #   version:
  #     counter: 43
  #
  # - name: sn-tm-trigger
  #   type: trigger
  #   version:
  #     counter: 24
  #
  # - name: sn-ddc-trigger
  #   type: trigger
  #   version:
  #     counter: 2

  # - name: sn-dcl-trigger
  #   type: trigger
  #   version:
  #     counter: 29
  # #
  # - name: sn-gke-trigger
  #   type: trigger
  #   version:
  #     counter: 1
  # #
  - name: sn-ecs-trigger
    type: trigger
    version:
      counter: 12

  # - name: sn-ecs-lb-trigger
  #   type: trigger
  #   version:
  #     counter: 15
  #
  # - name: sn-mix-a-trigger
  #   type: trigger
  #   version:
  #     counter: 4
  #
  # - name: sn-mix-b-trigger
  #   type: trigger
  #   version:
  #     counter: 7
