jobs:
  - name: sn-man
    type: manifest
    steps:
      - GET: sn-sn
      - GET: triggertest2

  - name: x4-gke
    type: gkeDeploy
    options:
      deployMethod: blueGreen
    steps:
      - GET: sn-man
      - GET: sn-gke


  # - name: sn-gke-deploy
  #   type: gkeDeploy
  #   steps:
  #     - GET: sn-man
  #     - GET: sn-gke

  # - name: bg-gke
  #   type: gkeDeploy
  #   options:
  #     deployMethod: blueGreen
  #   steps:
  #     - GET: sn-man
  #     - GET: sn-gke
