pipelines:
  - name: test_pipeline
    steps:
      - name: test_basic_execute
        type: powershell
        execution:
          onExecute:
            - Write-Output "hi"

      - name: test_basic_multicmd_execute
        type: powershell
        execution:
          onExecute:
            - Write-Output "hi"
            - Write-Output "hello"
