resources:
   - name: sample-w
     type: webhook
     configuration:
       integrationName: sample-webhook
     initialVersion:
       payload: test_payload
       
pipelines:
  - name: test_pipeline_1
    setup:
      environmentVariables:
        normal:
          - ENV1: value-pipe-1
          - ENV2: value-pipe-2
      runtime: onHost-pipe
    steps:
      - name: in_trigger_step
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          environmentVariables:
            normal:
              - ENV1: value1
              - ENV2: value2
          runtime: onHost
        triggeredBy:
          resources:
            - sample-w
        execution:
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
