pipelines:
  - name: test_pipeline
    steps:
      - name: say_hello
        type: bash
        execution:
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
