resources:
  - name: sample_img	
    type: image	
    imageName: scriptnull/sample_node	
    configuration:	
      integrationName: dockerint	
    initialVersion:	
      imageTag: latest

pipelines:
  - name: temp_test_pipeline
    steps:
      - name: say_hi
        type: bash
        configuration:
          nodePool: u16
        triggeredBy:	
          resources:	
            - sample_img
        execution:
          onComplete:
            - echo "this is on complete"
            - echo "CURRENT_SCRIPT_SECTION = $CURRENT_SCRIPT_SECTION"
          onSuccess:
            - echo "this is on success"
            - echo "CURRENT_SCRIPT_SECTION = $CURRENT_SCRIPT_SECTION"
          onExecute:
            - echo "hi"
            - echo "CURRENT_SCRIPT_SECTION = $CURRENT_SCRIPT_SECTION"
