pipelines:
  - name: test_pipeline
    steps:
      - name: test_basic_execute
        type: powershell
        execution:
          onExecute:
            - Write-Output "hi"

      - name: test_basic_multicmd_execute
        type: powershell
        execution:
          onExecute:
            - Write-Output "hi"
            - Write-Output "hello"

      - name: test_basic_throw_execute
        type: powershell
        execution:
          onExecute:
            - Write-Output "starting"
            - Throw "sample_error"
            - Write-Output "after error
