pipelines:
  - name: test_pipeline
    steps:
      - name: test_basic_execute
        type: powershell
        execution:
          onExecute:
            - Write-Output "hi"

      - name: test_basic_multicmd_execute
        type: powershell
        execution:
          onExecute:
            - Write-Output "hi"
            - Write-Output "hello"

      - name: test_basic_throw_execute
        type: powershell
        execution:
          onExecute:
            - Write-Output "starting"
            - Throw "sample_error"
            - Write-Output "after error

      - name: test_basic_full_execute
        type: powershell
        execution:
          onComplete:
            - Write-Output "starting onComplete"
            - Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
          onExecute:
            - Write-Output "starting onExecute"
            - Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
