resources:
  - name: w_git_resource
    type: gitRepo
    repoPath: scriptnull/sample_node
    configuration:
      integrationName: github
      branches:
        only: j-gitrepo
    initialVersion:
      sha: j-gitrepo
      
  - name: w_out_webhook
    type: webhook
    configuration:
      integrationName: out-webhook-int
    initialVersion:
      payload: "hello"
      
  - name: imageName
    type: image
    imageName: drydock/w19node
    configuration:
      integrationName: dockerint
    initialVersion:
      imageTag: master

pipelines:
  - name: test_pipeline
    steps:
      - name: start
        type: powershell
        requires:
          resources:
            - w_git_resource
        execution:
          onExecute:
            - Write-Output "hi"

      - name: test_basic_execute
        type: powershell
        requires:
          steps:
            - start
        execution:
          onExecute:
            - Write-Output "hi"

      - name: test_basic_multicmd_execute
        type: powershell
        requires:
          steps:
            - start
        execution:
          onExecute:
            - Write-Output "hi"
            - Write-Output "hello"
            - Get-ChildItem env:*

      - name: test_basic_throw_execute
        type: powershell
        requires:
          steps:
            - start
        execution:
          onExecute:
            - Write-Output "starting"
            - Throw "sample_error"
            - Write-Output "after error

      - name: test_basic_full_execute
        type: powershell
        requires:
          steps:
            - start
        execution:
          onStart:
            - Write-Output "starting onStart"
            - Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
          onExecute:
            - Write-Output "starting onExecute"
            - Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
          onSuccess:
            - Write-Output "starting onSuccess"
            - Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
          onComplete:
            - Write-Output "starting onComplete"
            - Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
            
      - name: test_basic_execute_failure
        type: powershell
        requires:
          steps:
            - start
        execution:
          onStart:
            - Write-Output "starting onStart"
            - Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
          onExecute:
            - Write-Output "starting onExecute"
            - Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
            - cat invalid-file.txt
            - Write-Output "this should not be executed"
          onSuccess:
            - Write-Output "starting onSuccess"
            - Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
          onFailure:
            - Write-Output "starting onFailure"
            - Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
          onComplete:
            - Write-Output "starting onComplete"
            - Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
            
      - name: test_output_external_webhook
        type: powershell
        requires:
          steps:
            - start
        outputResources:
          - w_out_webhook
        execution:
          onExecute:
            - Write-Output "hi"
            - Get-ChildItem env:*

