jobs:
  - name: sn-al-ship-man
    type: manifest
    steps:
      - IN: sn-al-ship-myapp2
      - IN: sn-al-ship-do
      - IN: sn-al-ship-ecs-trigger
      # - IN: sn-al-ship-scaler
      # - IN: sn-al-ship-trigger-1

  - name: sn-al-ship-ecs-dep-bgx-n
    type: deploy
    steps:
      - IN: sn-al-ship-man
      - IN: sn-al-ship-do-over
      - IN: sn-al-ship-ecs-cluster

  # - name: sn-al-ship-ecs-dep-upx
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-man
  #     - IN: sn-al-ship-ecs-cluster
  #     - TASK: managed
  #       deployMethod: upgrade
  #
  # - name: sn-al-ship-ecs-dep-replx
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-man
  #     - IN: sn-al-ship-ecs-cluster
  #     - TASK: managed
  #       deployMethod: replace

  # - name: sn-al-ship-ecs-dep-2
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-man
  #     - IN: sn-al-ship-ecs-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: sn-al-ship-tri-man
  #   type: manifest
  #   steps:
  #     - IN: sn-al-ship-dk
  #     # - IN: sn-al-ship-tesing-do
  #     - IN: sn-al-ship-tm-trigger
  #
  # - name: sn-al-ship-tri-dep-1
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-tri-man
  #     - IN: sn-al-ship-tri-cluster
  #
  # - name: sn-al-ship-tri-man-2
  #   type: manifest
  #   steps:
  #     - IN: sn-al-ship-ep
  #     - IN: sn-al-ship-tm-trigger-2
  #
  # - name: sn-al-ship-tri-dep-2
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-tri-man-2
  #     - IN: sn-al-ship-tri-cluster

  # - name: sn-al-ship-gke-man
  #   type: manifest
  #   steps:
  #     - IN: sn-al-ship-dk
  #     - IN: sn-al-ship-docker-opts-2
  #     - IN: sn-al-ship-gke-trigger
  #
  # - name: sn-al-ship-gke-dep
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-gke-man
  #     - IN: sn-al-ship-gke-cluster
  #
  #
  # - name: sn-al-ship-ddc-man-xx
  #   type: manifest
  #   steps:
  #     - IN: sn-al-ship-ep
  #     - IN: sn-al-ship-ddc-trigger
  #
  # - name: sn-al-ship-release-man-xx
  #   type: release
  #   steps:
  #     - IN: sn-al-ship-version
  #     - IN: sn-al-ship-ddc-man-xx
  #     - TASK: managed
  #       bump: patch

  # - name: sn-al-ship-ddc-dep-xx
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-release-man-xx
  #     - IN: sn-al-ship-ddc-cluster
  #
  # - name: sn-al-ship-release-ddc-xx
  #   type: release
  #   steps:
  #     - IN: sn-al-ship-ddc-dep-xx
  #     - TASK: managed
  #       bump: beta
  #
  # - name: sn-al-ship-ddc-man-yy
  #   type: manifest
  #   steps:
  #     - IN: sn-al-ship-dk
  #
  # - name: sn-al-ship-release-ddc-yy-1
  #   type: release
  #   steps:
  #     - IN: sn-al-ship-version
  #     - IN: sn-al-ship-ddc-man-yy
  #     - TASK: managed
  #       bump: major
  #
  # - name: sn-al-ship-release-ddc-yy-2
  #   type: release
  #   steps:
  #     - IN: sn-al-ship-release-ddc-yy-1
  #     - TASK: managed
  #       bump: alpha
  #
  # - name: sn-al-ship-release-ddc-yy-3
  #   type: release
  #   steps:
  #     - IN: sn-al-ship-release-ddc-yy-2
  #     - TASK: managed
  #       bump: beta
  #
  # - name: sn-al-ship-ddc-man-zz
  #   type: manifest
  #   steps:
  #     - IN: sn-al-ship-ep
  #
  # - name: sn-al-ship-ddc-dep-zz
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-ddc-man-zz
  #     - IN: sn-al-ship-ddc-cluster
  #
  # - name: sn-al-ship-release-zz-2
  #   type: release
  #   steps:
  #     - IN: sn-al-ship-ddc-dep-zz
  #     - IN: sn-al-ship-version
  #     - TASK: managed
  #       bump: major
  #
  # - name: sn-al-ship-ddc-dep-zz-3
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-release-zz-2
  #     - IN: sn-al-ship-ddc-cluster
  #
  # - name: sn-al-ship-release-zz-3
  #   type: release
  #   steps:
  #     - IN: sn-al-ship-ddc-dep-zz-3
  #     - TASK: managed
  #       bump: beta
  #
  #
  # - name: sn-al-ship-release-star-wars
  #   type: release
  #   steps:
  #     - IN: sn-al-ship-release-ddc-yy-3
  #     - IN: sn-al-ship-release-zz-3
  #     - IN: sn-al-ship-version
  #     - TASK: managed
  #       bump: major

  # - name: sn-al-ship-beta-ddc
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-release-ddc
  #     - IN: sn-al-ship-ddc-cluster
  #
  # - name: sn-al-ship-beta-release-1
  #   type: release
  #   steps:
  #     - IN: sn-al-ship-beta-version
  #     - IN: sn-al-ship-beta-ddc
  #     - TASK: managed
  #       bump: beta

  # - name: sn-al-ship-ecs-man-bg
  #   type: manifest
  #   steps:
  #     - IN: sn-al-ship-myapp3
  #     - IN: sn-al-ship-do
  #     - IN: sn-al-ship-ecs-trigger
  #
  # - name: sn-al-ship-ecs-deploy-bg
  #   type: deploy
  #   steps:
  #     - IN: sn-al-ship-ecs-man-bg
  #     - IN: sn-al-ship-ecs-cluster
  #     - IN: q-lb-loadbalancer1
  #       applyTo:
  #         - manifest: sn-al-ship-ecs-man-bg
  #           image: sn-al-ship-myapp3
  #           port: 80


  - name: sn-al-ship-ddc-man
    type: manifest
    steps:
      - IN: sn-al-ship-myapp3
      - IN: sn-al-ship-ddc-trigger

  - name: sn-al-ship-ddc-man-1
    type: manifest
    steps:
      - IN: sn-al-ship-myapp2
      - IN: sn-al-ship-ddc-trigger
  #
  - name: sn-al-ship-ddc-dep
    type: deploy
    steps:
      - IN: sn-al-ship-ddc-man-1
      - IN: sn-al-ship-ddc-man
      - IN: sn-al-ship-ddc-cluster

  - name: sn-al-ship-dcl-man
    type: manifest
    steps:
      - IN: sn-al-ship-dk
      # - IN: sn-al-ship-dcl-trigger

  - name: sn-al-ship-dcl-1
    type: deploy
    steps:
      - IN: sn-al-ship-dcl-man
      - IN: sn-al-ship-dcl-cluster

  - name: sn-al-ship-dcl-r-man
    type: manifest
    steps:
      - IN: sn-al-ship-dk
      - IN: sn-al-ship-scaler
      - IN: sn-al-ship-dcl-trigger

  - name: sn-al-ship-dcl-r-02
    type: deploy
    steps:
      - IN: sn-al-ship-dcl-r-man
      - IN: sn-al-ship-dcl-cluster
      - TASK: managed
        deployMethod: upgrade

  - name: sn-al-ship-kube-man
    type: manifest
    steps:
      - IN: sn-al-ship-dk
      - IN: sn-al-ship-kube-trigger

  - name: sn-al-ship-kube-depx
    type: deploy
    steps:
      - IN: sn-al-ship-kube-cluster

  - name: sn-al-ship-kube-upgr
    type: deploy
    steps:
      - IN: sn-al-ship-kube-man
      - IN: sn-al-ship-kube-cluster
      - TASK: managed
        deployMethod: upgrade
