triggers:
  - name: sn-al-ship-chain-trigger
    type: trigger
    version:
      counter: 4

  - name: sn-al-ship-file-trigger
    type: trigger
    version:
      counter: 20

  - name: sn-al-ship-runSh-trigger
    type: trigger
    version:
      counter: 2

  - name: sn-al-ship-trigger-1
    type: trigger
    version:
      counter: 9

  - name: sn-al-ship-tm-trigger
    type: trigger
    version:
      counter: 6

  - name: sn-al-ship-tm-trigger-2
    type: trigger
    version:
      counter: 4

  - name: sn-al-ship-ddc-trigger
    type: trigger
    version:
      counter: 3

  - name: sn-al-ship-gke-trigger
    type: trigger
    version:
      counter: 6

  - name: sn-al-ship-ecs-trigger
    type: trigger
    version:
      counter: 8

  - name: sn-al-ship-mix-a-trigger
    type: trigger
    version:
      counter: 4

  - name: sn-al-ship-mix-b-trigger
    type: trigger
    version:
      counter: 3
