jobs:
  # - name: sn-man-1
  #   type: manifest
  #   steps:
  #     - IN: sn-ep
  #     - IN: sn-docker-opts-1
  #     - IN: sn-trigger-1
  #
  # - name: sn-ecs-dep
  #   type: deploy
  #   steps:
  #     - IN: sn-man-1
  #     - IN: sn-ecs-cluster
  #
  - name: sn-tri-man
    type: manifest
    steps:
      - IN: sn-ep
      # - IN: sn-docker-opts-1
      - IN: sn-tm-trigger

  - name: sn-tri-dep-1
    type: deploy
    steps:
      - IN: sn-tri-man
      - IN: sn-tri-cluster

  # - name: sn-gke-man
  #   type: manifest
  #   steps:
  #     - IN: sn-dk
  #     # - IN: sn-docker-opts-1
  #     - IN: sn-gke-trigger

  # - name: sn-gke-dep
  #   type: deploy
  #   steps:
  #     - IN: sn-gke-man
  #     - IN: sn-gke-cluster


  - name: sn-ddc-man
    type: manifest
    steps:
      - IN: sn-ep
      - IN: sn-ddc-trigger

  - name: sn-ddc-dep
    type: deploy
    steps:
      - IN: sn-ddc-man
      - IN: sn-ddc-cluster
