pipelines:
  - name: fail_pipeline
    steps:
      - name: test_default_requires_invalid_resource
        type: powershell
        requires:
          resources:
            - invalid-resource-1
        execution:
          onExecute:
            - Get-ChildItem env:*
